# Generated by Django 5.2.7 on 2025-10-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(blank=True, to='projects.tag'),
        ),
    ]
